### ISSUE TITLE
multi-word exact matches at the start of a title aren't always first in the list of search results

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/catalogue-api#466]
> Hi gang, search ranking question - I was trying to find the book "Information Law", by searching on those words:  https://wellcomecollection.org/works?query=information+law. As you can see the book doesn't show up until about half way down the second page of hits, even though the words are an exact match to the first two words of the title. Is that to be expected (because the book's works page isn't very popular or something?). If I add the author name to the search, then it shows up as the only hit (the book is https://wellcomecollection.org/works/zkg7xqm7).

**Comment by harrisonpim** [comment]
the current query is prioritising matches in the `search.relations`, which has no positional awareness. we don't currently prioritise proximity to the start of a title (or any other field)

**Comment by harrisonpim** [comment]
The 'correct' result for this query can be brought back by adding a [span_first](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-span-first-query.html) query:

```json
{
  "query": {
    "bool": {
      "should": [
        {
          "span_first": {
            "match": {
              "span_term": {
                "data.title.shingles": "information law"
              }
            },
            "end":1,
            "boost":1000
          }
        },
        {
          "multi_match": {
...
```

**Comment by harrisonpim** [comment]
I'd like to investigate the effect of
- turning down the boost on the relations field vs
- adding the `span_first` to `title.shingles`
using the standard set of rank tools before making any changes to the prod query

**Comment by pollecuttn** [comment]
Issue first reported on Slack at https://wellcome.slack.com/archives/C8X9YKM5X/p1653293886888919
