### ISSUE TITLE
why is rank failing?

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/catalogue-api#469]

**Comment by harrisonpim** [comment]
rank is failing two alternative-spelling tests: 

```json
{ "query": "travaillons", "ratings": ["jb823ud6"] },
{ "query": "conosceva", "ratings": ["va2vy7wb"] },
```

these works ([jb823ud6](https://wellcomecollection.org/works/jb823ud6), [va2vy7wb](https://wellcomecollection.org/works/va2vy7wb)) should appear anywhere in the list of results for those terms

**Comment by harrisonpim** [comment]
Hunting a hunch that this is related to the analysis, I've run the following in dev tools

```
GET /_analyze
{
  "filter": [
    "lowercase",
    {
      "name": "italian",
      "type": "stemmer"
    }
  ],
  "tokenizer": "standard",
  "text": "conosceva"
}
```

```
GET /_analyze
{
  "filter": [
    "lowercase",
    {
      "name": "italian",
      "type": "stemmer"
    }
  ],
  "tokenizer": "standard",
  "text": "conoscenza"
}
```

Looking for how the italian analyser breaks down the search term ("conosceva") and the term in the title which we expect to match ("conoscenza")

For "conosceva" we get:

```
{
  "tokens" : [
    {
      "token" : "conosc",
      "start_offset" : 0,
      "end_offset" : 9,
      "type" : "<ALPHANUM>",
      "position" : 0
    }
  ]
}
```

and for  "conoscenza" we get

```
{
  "tokens" : [
    {
      "token" : "conoscent",
      "start_offset" : 0,
      "end_offset" : 10,
      "type" : "<ALPHANUM>",
      "position" : 0
    }
  ]
}
```

I'm not sure what's changed but this is obv the underlying problem

**Comment by harrisonpim** [comment]
The french example is even weirder:
- `travaillons` becomes `travailon`
- `travaillent` becomes `travailent`

**Comment by alexwlchan** [comment]
My theory was that it was something to do with my inlining of `WorksAnalysis.languages` here: https://github.com/wellcomecollection/catalogue-api/pull/467/files#diff-f06c3b2d3925e97ed7bb54c6c9049d4951c5874c47bac88f5adf33029deabe21

But I don't think that's it; the variable looks correct.

**Comment by harrisonpim** [comment]
tbf, i think the conosceva example might be a poor choice by us in the first place. "Conosceva" means "he knew" and "conoscenza" means "knowledge", so a change of work ID there to something more relevant might not be the worst thing in the world...

**Comment by alexwlchan** [comment]
To be sure, I looked at those analyses in both 7.16.3 (the old rank cluster) and 7.17.4 (the new cluster); both of them return the same analysis as above.

**Comment by alexwlchan** [comment]
To poke holes in another theory: I have a snapshot taken in April's and the title of va2vy7wb hasn't changed. It's still conoscenza.
