### ISSUE TITLE
Test discovery is broken in search

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/catalogue-api#589]
Running `./builds/run_sbt_task_in_docker.sh "project search" "dockerComposeTest"` (same as the buildkite command) runs 32 tests.

There are (I believe) 262 tests in the search project.

**Comment by paul-butcher** [comment]
This appears to have occurred with this change, which (I think) changes it to run `dockerComposeTest` instead of run_sbt_task_in_docker 

https://github.com/wellcomecollection/catalogue-api/commit/95a1f910cbdc2b31ca1e256b5606c2cc9536f60f#diff-8fd74420ca55aa91d4c53775d2a55a999c405b5a4fafeaf73b7f0ef83e1f3b0c

**Comment by alexwlchan** [comment]
oh nuggets, maybe that command is wrong

if that's wrong and we actually want `;dockerComposeUp;test;dockerComposeStop`, we should fix it everywhere.

**Comment by paul-butcher** [comment]
This has revealed some (42) failing tests.  I have fixed a few (which were from https://github.com/wellcomecollection/catalogue-api/pull/575).  More investigation to follow.

**Comment by paul-butcher** [comment]
I am a bit confused about the point of these tests:
https://github.com/wellcomecollection/catalogue-api/blob/main/search/src/test/scala/weco/api/search/images/ImagesSimilarityTest.scala

Each of them loads a bunch of documents into Elastic, then requests one of them, comparing it to the "expected response".  The difference between each expected response is the presence of an empty list, corresponding to the given query string parameter:, eg. `includes visually similar images with ?include=visuallySimilar` contains  `"visuallySimilar":[]` etc.  Otherwise, it's just the document as stored.

https://github.com/wellcomecollection/catalogue-api/blob/main/search/src/test/resources/expected_responses/visually-similar-features-and-palettes.json


(@harrisonpim it has been this way since https://github.com/wellcomecollection/catalogue-api/commit/4f6fb109a9f4af10c42a73495ee410577ba8892b)

**Comment by paul-butcher** [comment]
This is sorted now.  It revealed some broken tests and broken behaviour, which I have now resolved.
https://github.com/wellcomecollection/catalogue-api/pull/591

https://github.com/wellcomecollection/catalogue-pipeline/pull/2272
