### ISSUE TITLE
Define queries using normal Elasticsearch JSON

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/catalogue-api#662]
Currently, we define queries (e.g. [weco.api.search.elasticsearch.WorksMultiMatcher](https://github.com/wellcomecollection/catalogue-api/blob/5fae7b8f1b91c54be77f2c0bfc4fa5c63f7c0760/search/src/main/scala/weco/api/search/elasticsearch/WorksMultiMatcher.scala#L20)) using the Elastic4s DSL, but during development and refinement of those queries (e.g. when @harrisonpim is coming up with new exciting ways to query the data), we work with the JSON itself directly.

As a result, we end up translating normal ES query JSON into Elastic4S DSL just so that Elastic4s can translate it back again.

Instead, we should define the queries as either a Query Template in Elastic, or as a string template that generates the JSON.

That would make it easier to maintain.

**Comment by paul-butcher** [comment]
We have already been bitten by the difference between E4S and ES WRT [KNN Queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html), (E4S does not (yet) support them) which I resolved by [programmatically creating some JSON](https://github.com/wellcomecollection/catalogue-api/blob/5fae7b8f1b91c54be77f2c0bfc4fa5c63f7c0760/search/src/main/scala/weco/api/search/elasticsearch/ImagesQuery.scala#LL54C15-L54C23) and providing it as a raw query to E4S.

**Comment by paul-butcher** [comment]
In the query definitions, we use commentary to help describe the intent behind the various parts of the query.

This is facilitated by it being scala code that programmatically creates a query.  In JSON, this is not directly possible.

How can I best manage this?

**Comment by harrisonpim** [comment]
> In the query definitions, we use commentary to help describe the intent behind the various parts of the query.
> 
> This is facilitated by it being scala code that programmatically creates a query. In JSON, this is not directly possible.
> 
> How can I best manage this?

Very interested in any ideas you have for solving that problem!

I've used [named queries](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-bool-query.html#named-queries) to add commentary to queries in the past, but that solution has always felt a bit hacky/incomplete... 

Also, we can't apply the same kind of commentary in JSON for index mappings/settings config, which is usually where the interesting and complicated stuff ideas hide.

**Comment by paul-butcher** [comment]
Filters still need to be built up programmatically somehow, and combined with the search part of the query that comes from the template.

**Comment by paul-butcher** [comment]
I wonder if, rather than the obvious method of using a resource file, we might be able to provide commentary by defining the JSON in a bunch of multiline strings that get concatenated.

Almost taking a sort of Literate Programming approach.

**Comment by paul-butcher** [comment]
It is possible to template the filters, with a construction that looks like this (this is just two filters, so would need to be extended to cover all of them):
```
{
  "bool": {
    "must": [
      {
        "term": {
          "type": {
            "value": "Visible"
          }
        }
      },
      {{#format}}
      {
        "terms": {
          "query.languages.id": {{#toJson}}format,{{/toJson}}
        }
      }
      {{^format}}
      {
        "match_all": {}
      }
      {{/format}},
      {{#languages}}
      {
        "terms": {
          "query.languages.id": {{#toJson}}languages{{/toJson}}
        }
      }
      {{^languages}}
      {
        "match_all": {}
      }
      {{/languages}},
      {{#availabilities}}
      {
        "terms": {
          "query.availabilities.id": {{#toJson}}availabilities{{/toJson}}
        }
      }
      {{^availabilities}}
      {
        "match_all": {}
      }
      {{/availabilities}}
    ]
  }
}
```

Templating is quite crude (no and/or/first/last etc.), so the `match_all` business is a way to get round having to work out whether there are any preceding or following filters in order to choose whether to put a comma in.

The trouble is that this would have to be replicated across all the aggregations as well (with each aggregation being slightly different because it would omit its paired filter).

**Comment by paul-butcher** [comment]
So one (future) option could be to programmatically generate a stored template like this, but I think it's too unwieldy to maintain manually.

Similarly, sending a template like this to `_search/template` in the `source` field (as an escaped string, no less) would also be a bit of a big request, and it would be hard to read when debugging.

**Comment by paul-butcher** [comment]
hmm.  it doesn't look like e4s can handle search/template like this

**Comment by paul-butcher** [comment]
https://github.com/wellcomecollection/catalogue-api/pull/682

**Comment by harrisonpim** [comment]
I've stashed the candidate mappings/queries I've been working on [over here, in the rank repo](https://github.com/wellcomecollection/rank/tree/main/candidates). I hope they're a useful foundation for future work!
