### ISSUE TITLE
Proposed process for off-site requesting

### ISSUE THREAD

**Issue by jcateswellcome** [wellcomecollection/catalogue-api#744]
Put together a high-level user journey, diagramatically, from the point of requesting online:

- To illustrate the current process, and what happens if a user runs into something that they cannot request. 
- To propose a user journey that incorporates the option to request for these items.

The output will be a Miro board and the aim is to show:

- A hypothetical user journey
- Steps that will or might be automated/systematised
- Any messaging for or to users (to include on-screen messages, emails, and visibility of requests in their library account)
- Steps that will or may be manual or require mediation

Link to epic: https://www.notion.so/wellcometrust/Enable-off-site-requesting-MVP-f6ab9f0903d84623a6da6d168017ec51?pvs=4

**Comment by jcateswellcome** [comment]
[Miro board ](https://miro.com/app/board/uXjVN28SFgM=/)

**Comment by pollecuttn** [comment]
@jcateswellcome can this be closed now?

**Comment by jcateswellcome** [comment]
@pollecuttn yes I think we don't need this ticket now
