### ISSUE TITLE
Guard against "Head of empty list" errors in Sierraitemupdater

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/catalogue-api#759]
We keep getting alerted to 5xx errors occurring when an item has no accessConditions. 
https://wellcome.slack.com/archives/CQ720BG02/p1709821702412539

https://wellcome.slack.com/archives/CQ720BG02/p1709817801997699

**Comment by pollecuttn** [comment]
I can't see status or access - is that my internet or a problem for us?
![image](https://github.com/wellcomecollection/catalogue-api/assets/1446072/87cd71d1-fdeb-4c07-97ad-105e92ef249d)

**Comment by pollecuttn** [comment]
But I can see them on the OPAC:
![image](https://github.com/wellcomecollection/catalogue-api/assets/1446072/341f64e7-9bd1-4174-be17-b35934793fc0)

**Comment by paul-butcher** [comment]
> I can't see status or access - is that my internet or a problem for us?

Yes, I think that is our problem. I think this will fix that, but there may be something sending us dodgy data elsewhere.
