### ISSUE TITLE
[offsiteReq] Phase 1: next steps

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/catalogue-api#783]
RFC: https://github.com/wellcomecollection/docs/blob/main/rfcs/060-offsite-item-requesting/README.md

1. ✅ Determine which combination(s) of Sierra fields:value indicates that an item is held offsite [#785](https://github.com/wellcomecollection/catalogue-api/issues/785)
2. ✅ Add DeepStore as a Venue in Prismic, so that it can be indexed in the contentAPI's venue index. ~~Extend the length of the list of `NextOpeningDays` to accommodate DeepStore's longer leadTimeInDays~~ actually we only care above the next 10 working days [#786](https://github.com/wellcomecollection/catalogue-api/issues/786)
3. Update [SierraItemUpdater](https://github.com/wellcomecollection/catalogue-api/blob/main/items/src/main/scala/weco/api/items/services/SierraItemUpdater.scala) to get the item's location code from Sierra, fetch the corresponding venueOpeningTimes and apply the correct leadTimeInDays. [#787](https://github.com/wellcomecollection/catalogue-api/issues/787)
4. Update catalogue-pipeline so that DeepStore items are indexed with the correct locations data [#2657](https://github.com/wellcomecollection/catalogue-pipeline/issues/2657)

Bonus issue: [#788](https://github.com/wellcomecollection/catalogue-api/issues/788)

**Comment by jcateswellcome** [comment]
part of #784

**Comment by agnesgaroux** [comment]
Make sure tho update this checker "isRequestable" as only returns `true` for "online-request" items
/Users/agnesgaroux/wellcome/catalogue-api/common/stacks/src/main/scala/weco/api/stacks/models/DisplayItemOps.scala
