### ISSUE TITLE
[offsiteReq] Update SierraItemUpdater to add availabilitySlots for DeepStore items

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/catalogue-api#787]
Pull in the item's location code from Sierra when we get its access conditions [here](https://github.com/wellcomecollection/catalogue-api/blob/c4a062b8d5f75d839f658a61afc5846ea700337d/items/src/main/scala/weco/api/items/services/SierraItemUpdater.scala#L64) then use it in `getAvailableDates` to figure out whether it's DeepStore (harop) or onsite (any other location code)

If it's DeepStore, fetch the venue from content-api and apply correct `LeadTimeInDays`

❓I don't think the location code should be part of the `DisplayAccessCondition` since it's not something we want to display on the work page. We could include it and let wc.org ignore it, or refactor `updateItems` so that it handles items one by one which I believe would keep things are bit cleaner 

-> there will be some slight complication around the available dates **after** the first
- first available date is dependent on DeppStore working days. Alexandra confirmed it's [any day other than Saturdays, Sundays and public holidays](https://wellcome.slack.com/archives/C05JE6PE5PG/p1716999415777119?thread_ts=1716998691.301479&cid=C05JE6PE5PG)
- the following days are dependent on the library opening days: once the item is onsite it can be viewed in the library any day it is open
- Therefore we'll need to fetch both DeeptStore and Library venues for DeepStore items. The 1st `AvailabilitySlot` will be the day the item is delivered, then the following ones will be library opening days

**Comment by agnesgaroux** [comment]
Rules for DeepStore leadTimeInDays

The logic as I understand it is:
- 10 DeepStore working days to get the item back on site
- After that the item can be viewed any day that the library is open

If I make a request on Monday 3rd June:
- the item will be delivered on site on Friday 14th June
- it can be viewed Saturday 15th June, then Monday 17th to Saturday 22nd and Monday 24th to Friday 28th (the current choice of 12 days to pick from)
- If there were x public holidays between Monday 3rd June and Friday 14th June, the delivery date would be postponed by as many days

That's assuming, TBC, that:
- the day of the request (Monday 3rd June) is day 1 of the 10 days DeepStore lead time, not day 0
- the item cannot be viewed on the day it is delivered, but the next day the library is open
- we give the user a 12 opening day window to come on site to view the item once it's been delivered. If they want to see it at a later date, they ned to make the request at a later date

**Comment by agnesgaroux** [comment]
Email sent to LE&E to confirm the above points

**Comment by pollecuttn** [comment]
As well as public holidays there's also the longer Christmas closure, which changes every year and is put into the library opening times by Editorial.
